### ISSUE TITLE
《自动化持续集成》-- gitlab CI

### ISSUE THREAD

**Issue by zhengguorong** [zhengguorong/articles#25]
### gitlab安装
安装比较简单，跟着官网的教程，复制粘贴命令
参考地址：https://about.gitlab.com/installation/#ubuntu
安装完毕后浏览器输入服务器地址，gitlab默认使用80端口，如果正常打开，输入密码，默认账户为root。

### gitlab-runner安装
因为gitlab CI需要依赖gitlab-runner执行任务，我们也还是按官方教程安装。
参考地址：https://docs.gitlab.com/runner/install/linux-repository.html

### docker安装
gitlab-runner需要依赖docker作为构建环境，当然这不是非必要，你可以选择其他依赖，不过个人建议还是用docker比较方便。
docker安装参考地址：https://docs.docker.com/install/linux/docker-ce/ubuntu/

### 配置runner
gitlab-runner需要和gitlab做绑定，因此需要执行register操作。
1、执行以下命令
```
sudo gitlab-runner register
```
2、输入gitlab实例地址
```
Please enter the gitlab-ci coordinator URL (e.g. https://gitlab.com )
https://gitlab.com（这个地址是你安装gitlab服务器地址）
```
3、输入token，可以在CI/CD菜单下Runners查看token
```
Please enter the gitlab-ci token for this runner
xxx
```
![image](https://user-images.githubusercontent.com/2757932/45740012-d00b9800-bc26-11e8-8001-8e7f0b3e2dfc.png)
4、给你的runner输入个描述内容，随便填就好
```
Please enter the gitlab-ci description for this runner
[hostame] my-runner
```
5、给你的runner设置tag，随便输入
```
Please enter the gitlab-ci description for this runner
[hostame] my-runner
```
6、输入runner执行环境，我们用docker，你也可以用其他环境。
```
Please enter the executor: ssh, docker+machine, docker-ssh+machine, kubernetes, docker, parallels, virtualbox, docker-ssh, shell:
docker
```
7、配置默认docker镜像，用于当.gitlab-ci.yml没有配置时的镜像
```
Please enter the Docker image (eg. ruby:2.1):
alpine:latest
```
注册成功后，你可以在gitlab的settings -- CI/CD -- Runners看到如下图
![image](https://user-images.githubusercontent.com/2757932/45740477-f1b94f00-bc27-11e8-914b-a07db4a00806.png)

### 配置构建任务
在项目根目录新建.gitlab-ci.yml文件
```
image: node:8
stages:
  - test
  # - build
  
test:
  stage: test
  before_script:
    - npm install
  artifacts:
    expire_in: 30 day
    paths:
      - coverage/
  script:
    - npm run lint
    - npm run test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - 'node_modules/'
```
配置完毕后，当提交代码或者进行RP的时候，CI会自动执行构建任务，我们的配置文件执行两个任务，检查代码风格和执行单元测试。

**提交代码后，CI开始运行，如下图**

![image](https://user-images.githubusercontent.com/2757932/45741290-cc2d4500-bc29-11e8-9f71-7a738a8a074d.png)

**或者提交RP，走code review流程**

![image](https://user-images.githubusercontent.com/2757932/45748974-db69be00-bc3c-11e8-8b22-5c49426ae3cf.png)
